version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-torrent-bot
    restart: unless-stopped
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
